version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 22181:2181
    env_file:
      - ./.env

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
  
  #We need to wait until kafka ends. 
  streaming:
    build: 
      context: ./streaming
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - ./.env
networks:
  default:
    driver: bridge